@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class Webserver {
- {static} PORT :int
- {static} FORMATTER : DateTimeFormatter
+ Webserver()
}

class SocketThread {
- insocked : Socked
- makeRequest(tokens : String[]) : Request
- makeRequestReader(tokens : String[]) : RequestReader
- makeRequestArea(tokens : String[]) : RequestArea
- makeHeaderAnswer() : String
- makeJsonAnswer(request : Request) : String
+ run()
}

Webserver +-right- SocketThread

note right of SocketThread
inner class
of Webserver
end note

class DirectoryDoors {
- {static} allDoors : Door[]
+ {static} makeDoors()
+ {static} findDoorById(id : String) : Door
+ {static} getAllDoors() : Door[]
}

DirectoryDoors --> "*" Door : "allDoors"
Partition --> Area

class DirectoryUsers {
- {static} users : User[]
+ {static} makeUsers()
+ {static} findUserByCredential(credential : String) : User
}

DirectoryUsers --> "*" User : "users"

class DirectorySpaces {
-{static} allSpaces : Space[]
-{static} spaceNames : String[]
+{static} makeSpaces()
+{static} findDoorBySpaceId(id : String) : Door[]
+{static} getAllSpaces() : Space[]
}

DirectorySpaces --> "*" Space : "allSpaces"

class DirectoryPartitions {
-{static} allPartitions : Partition[]
-{static} partitionNames : String[]
+{static} makePartitions()
+{static} findDoorByPartitionId(id : String) : Door[]
+{static} getAllPartitions() : Partition[]
}

DirectoryPartitions --> "*" Partition : "allPartitions"

class DirectoryAreas {
- {static} allAreas : Area[]
+ {static} makeAreas()
+ {static} findAreaById(id : String) : Area


}

DirectoryAreas --> "*" Area : "allAreas"


class Door {
- id : String
- from : String
- to : String
- partition : String
- closed : boolean
- locked : boolean
- propped : boolean
- unlocked_shortly : boolean
+ Door(id : String, from : String, to : String, partition : String)
+ processRequest(request : RequestReader)
+ setState(doorState : DoorState)
+ toJson() : JSONObject
+ getId() : String
+ getFrom() : String
+ getTo() : String
+ getPartition() : String
'+ toString() : String
'+ isClosed() :boolean
'+ setClosed(b : boolean)
'+ getStateName() : String
- doAction(action : String)
}


class User {
- name : String
- credential : String
- role : String
+ getCredential() : String
+ getRole() : String
+ User(name: String, credential: String)
+ toString() : String
}

class Space extends Area{
+ Space(id : String, doors : Door[])
}

class Partition extends Area{
+ Partition(id : String, doors : Door[])
}

abstract class Area {
# id : String
# doors : Door[]
+ Area(id : String, doors : Door[])
+ getId() : String
+ setDoors(doors : Door[])
+ getDoorsGivingAccess() : Door[]
}


class Main {
+ {static} main(args : String)
}

note right of Main::main
DirectoryDoors.makeDoors()
DirectoryUsers.makeUsers()
DirectoryAreas.makeAreas()
new Webserver()
end note

Main -[hidden]down- Webserver
Webserver -[hidden]down- DirectoryDoors
DirectoryDoors -[hidden]right- DirectoryUsers
@enduml
